Update Dockerfile
OutSystems/cloud-connector pull request #21
Opened 2023-10-09 20:01 UTC by OS-kiranmalsetty

2023-10-10 14:02 UTC, joaomvalentim requested changes

2023-10-10 19:28 UTC, OS-kiranmalsetty commented on Dockerfile
> +COPY outsystemscc /outsystemscc
@joaomvalentim PR is updated. can you please review it again?

2023-10-11 16:15 UTC, joaomvalentim approved these changes

2023-11-29 14:58 UTC, bmartins-unit commented
Example working with the new entry point:
<img width="1036" alt="Screenshot 2023-11-29 at 14 54 59" src="https://github.com/OutSystems/cloud-connector/assets/59831763/49da52fd-60d6-455a-9f0b-158ed188cc6c">

2023-11-29 16:22 UTC, bmartins-unit commented
Example working with the new entry point:
<img width="1036" alt="Screenshot 2023-11-29 at 14 54 59" src="https://github.com/OutSystems/cloud-connector/assets/59831763/4c325bfa-1150-4a5c-a718-8b8709995fea">

2023-11-30 15:58 UTC, merged